### ISSUE TITLE
Questions About Project Webhooks

### ISSUE THREAD

**Issue by afh** [ledger/ledger.github.io#56]
Looking at this project's settings I came across the webhooks and have the following questions:

* [`http://ledger-cli.org:8888/ledger-cli.org`](https://github.com/ledger/ledger-website/settings/hooks/1253201)
  - Is this still in use?
  - If no, can this be deleted?
  - If yes, can this be migrated to `https`?
  
* [`https://notify.travis-ci.org`](https://github.com/ledger/ledger-website/settings/hooks/75768650)
  - **Deleted**  ~~Is this still in use?~~
  - ~~If no, can this be deleted?~~

**Comment by jwiegley** [comment]
I do not know...

**Comment by tbm** [comment]
I also don't know anything about this. Maybe @simonmichael does.

**Comment by simonmichael** [comment]
IIRC in the earliest days, before github pages, I hosted ledger-cli.org myself; and perhaps this caused PDFs to be regenerated or something.

**Comment by afh** [comment]
Thanks everyone for chiming in. I went ahead and deleted the webhook.
