### ISSUE TITLE
Website maintainership

### ISSUE THREAD

**Issue by peterkeen** [ledger/ledger.github.io#59]
I find myself with a very complicated life right now and no time to dedicate to maintenance of ledger-cli.org, which is a problem when it's sitting here broken.

As it stands, I personally own the S3 bucket and cloudfront endpoint that powers the site. @jwiegley owns the domain name (iirc) and has delegated DNS to a Route53 name server that I control.

@tbm @simonmichael @afh would one of you be willing to take over as chief maintainer? I would be happy to point the Route53 nameserver at whatever solution you decide makes sense as an interim solution until y'all figure out your own DNS hosting.

**Comment by afh** [comment]
Sorry to hear that you find yourself with a very complicated life, @peterkeen. Wishing you all the best and that things change for the better soon.

Happy to join forces with @tbm or @simonmichael or both or someone else to maintain ledger-cli.org. I'm rather unfamiliar with AWS and would possibly look into GitHub Pages that @simonmichael mentioned in #46.

@peterkeen could you give a rough estimate of the monthly/yearly cost of running ledger-cli.org on AWS?

**Comment by peterkeen** [comment]
@afh it's all tied into the same AWS account as everything else I do there so it's hard to tease out exactly. Route53 is 0.50 USD per month and it looks like S3 usage is about 0.75 USD per month. CloudFront looks like it fits into the free tier.

**Comment by afh** [comment]
Thanks for the information, @peterkeen, very helpful.

**Comment by afh** [comment]
Closing as I've effectively taken over. While I'm happy to being the first point of contact I'd love to share credentials to involved infrastructure with other maintainers to increase the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) and avoid a single point of failure.

@jwiegley, @simonmichael, @tbm, @purcell would you be okay receiving an encrypted email containing info and credentials about the infrastructure underlying ledger-cli.org?

Thank you, @peterkeen, for having maintained ledger-cli.org in the past :pray:
Hopefully you are doing reasonably well and life simplifies for you soon. Whenever your feel like contributing to ledger and ledger-cli.org again, know that you are always welcome 🙂

**Comment by tbm** [comment]
Yes, I'm ok with it.  This is my GPG key:

```
pub   rsa4096 2009-07-12 [SC]
      D866749DF7FCD903C32D01893D0787AAAF6C61DD
uid           [ultimate] Martin Michlmayr <tbm@cyrius.com>
sub   rsa4096 2009-07-12 [E]
```

**Comment by jwiegley** [comment]
Sure, my key is here: http://ftp.newartisans.com/pub/pubkey.asc

**Comment by afh** [comment]
@tbm In your comment above what you have shared may only be your key's keygrip, from which I'm unable to import it.

The following command should print out the key ID for your encryption sub-key: `gpg -K tbm@cyrius.com | awk -F '[ /]' '/\[E\]$/{print $4}'`, which I can then use to `gpg --recv-key` it.

**Comment by tbm** [comment]
```
pub   rsa4096 2009-07-12 [SC]
      D866749DF7FCD903C32D01893D0787AAAF6C61DD
uid           [ultimate] Martin Michlmayr <tbm@cyrius.com>
sub   rsa4096 2009-07-12 [E]
```

**Comment by afh** [comment]
Unfortunately my knowledge about GnuPG may be too little to successfully import your GPG key from the info you provided.

My assumption that `D866749DF7FCD903C32D01893D0787AAAF6C61DD` is your key's keygrip is wrong. Here's what I do to try and import your GPG key:

```
% gpg --recv-keys 0xD866749DF7FCD903C32D01893D0787AAAF6C61DD
gpg: key 0xAF6C61DD: no user ID
gpg: Total number processed: 1
% gpg -k 0xAF6C61DD
gpg: error reading key: No public key
```

@tbm given the difficulties I run into are you okay with sending me your exported public key via email (`gpg --armor --export pubkey.asc tbm@cyrius.com` from [*The GNU Privacy Handbook — Exchanging Keys*](https://www.gnupg.org/gph/en/manual/x56.html))?

**Comment by afh** [comment]
@jwiegley it seems your [public key](http://ftp.newartisans.com/pub/pubkey.asc) expired on 2021-11-25

```
% gpg -k jwiegley | grep ^pub
pub   rsa8192/0x7AC14BA2 2013-08-12 [SC] [expired: 2021-11-25]
```

I'm not sure how to send an encrypted email to you since gnupg refuses to use your expired key to encrypt the message. `neomutt` complains saying that `This key can't be used: expired/disabled/revoked` and `gnupg` considers the key unusable:

```
% gpg --batch --trust-model=always -ear 0x7AC14BA2  <<< test
gpg: 0x7AC14BA2: skipped: Unusable public key
gpg: [stdin]: encryption failed: Unusable public key
```
