### ISSUE TITLE
Redirect for old doc links

### ISSUE THREAD

**Issue by tbm** [ledger/ledger.github.io#68]
https://ledger-cli.org/3.0/doc/ledger3.html is now broken. @afh can you add a redirect?

**Comment by afh** [comment]
Great idea, @tbm. I'll add it next time I'm in front of workstation.

**Comment by afh** [comment]
I've deployed redirect rules for https://ledger-cli.org/3.0/doc/ledger3.html and https://ledger-cli.org/3.0/doc/ledger3.pdf on Cloudflare and they should already be live. Mind testing and closing this issue if tests have been successful, @tbm?

**Comment by tbm** [comment]
Works for me, thanks

**Comment by afh** [comment]
Thanks for confirming, @tbm.
